import Head from 'next/head'
import Image from 'next/image'
import Features from '../components/Features'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'

export  default function Home() {
    return (
        <div>
            <Head>
                <title>Next App </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NavBar/>
            <Hero/>
            <Features/>
           
           
        </div>
    )
}
